flowchart TD
    examples_embedded_refactor["examples.embedded_refactor<br/>1 funcs"]
    examples_k8s_debug["examples.k8s_debug<br/>1 funcs"]
    examples_polish_leasing["examples.polish_leasing<br/>1 funcs"]
    examples_providers["examples.providers<br/>17 funcs"]
    examples_python_sdk["examples.python_sdk<br/>11 funcs"]
    examples_quick_start["examples.quick_start<br/>12 funcs"]
    prellm_budget["prellm.budget<br/>11 funcs"]
    prellm_chains["prellm.chains<br/>10 funcs"]
    prellm_cli["prellm.cli<br/>24 funcs"]
    prellm_core["prellm.core<br/>17 funcs"]
    prellm_env_config["prellm.env_config<br/>12 funcs"]
    prellm_llm_provider["prellm.llm_provider<br/>6 funcs"]
    prellm_logging_setup["prellm.logging_setup<br/>3 funcs"]
    prellm_model_catalog["prellm.model_catalog<br/>2 funcs"]
    prellm_models["prellm.models<br/>2 funcs"]
    prellm_pipeline["prellm.pipeline<br/>18 funcs"]
    prellm_server["prellm.server<br/>9 funcs"]
    prellm_trace["prellm.trace<br/>16 funcs"]
    prellm_cli ==>|14| prellm_env_config
    examples_quick_start ==>|10| prellm_core
    examples_python_sdk ==>|8| prellm_core
    examples_polish_leasing -->|3| prellm_core
    examples_k8s_debug -->|3| prellm_core
    examples_embedded_refactor -->|3| prellm_core
    prellm_server -->|3| prellm_core
    examples_providers -->|2| prellm_core
    prellm_cli -->|2| prellm_budget
    prellm_cli -->|2| prellm_model_catalog
    prellm_core -->|2| prellm_trace
    examples_python_sdk -->|1| prellm_pipeline
    prellm_cli -->|1| prellm_logging_setup
    prellm_cli -->|1| prellm_core
    prellm_cli -->|1| prellm_server
    prellm_cli -->|1| prellm_models
    prellm_core -->|1| prellm_pipeline
    prellm_llm_provider -->|1| prellm_budget
    prellm_server -->|1| prellm_env_config
    prellm_chains -->|1| prellm_core
