flowchart TD
    examples__embedded_refactor["examples.embedded_refactor<br/>1 funcs"]
    examples__k8s_debug["examples.k8s_debug<br/>1 funcs"]
    examples__polish_leasing["examples.polish_leasing<br/>1 funcs"]
    examples__providers["examples.providers<br/>16 funcs"]
    examples__python_sdk["examples.python_sdk<br/>11 funcs"]
    examples__quick_start["examples.quick_start<br/>12 funcs"]
    examples__utils["examples.utils<br/>2 funcs"]
    prellm__agents["prellm.agents<br/>9 funcs"]
    prellm__budget["prellm.budget<br/>11 funcs"]
    prellm__chains["prellm.chains<br/>10 funcs"]
    prellm__cli["prellm.cli<br/>26 funcs"]
    prellm__core["prellm.core<br/>35 funcs"]
    prellm__env_config["prellm.env_config<br/>17 funcs"]
    prellm__llm_provider["prellm.llm_provider<br/>6 funcs"]
    prellm__logging_setup["prellm.logging_setup<br/>3 funcs"]
    prellm__model_catalog["prellm.model_catalog<br/>2 funcs"]
    prellm__models["prellm.models<br/>2 funcs"]
    prellm__pipeline["prellm.pipeline<br/>18 funcs"]
    prellm__server["prellm.server<br/>9 funcs"]
    prellm__trace["prellm.trace<br/>29 funcs"]
    prellm__utils["prellm.utils<br/>4 funcs"]
    examples__providers ==>|13| examples__utils
    prellm__cli ==>|13| prellm__env_config
    examples__python_sdk ==>|8| prellm__core
    examples__quick_start ==>|6| prellm__core
    examples__quick_start ==>|4| examples__utils
    examples__embedded_refactor -->|3| prellm__core
    examples__polish_leasing -->|3| prellm__core
    examples__k8s_debug -->|3| prellm__core
    prellm__server -->|3| prellm__core
    prellm__core -->|2| prellm__trace
    prellm__cli -->|2| prellm__model_catalog
    prellm__cli -->|2| prellm__budget
    prellm__agents -->|2| prellm__utils
    examples__utils -->|2| prellm__core
    examples__providers -->|1| prellm__core
    examples__python_sdk -->|1| prellm__pipeline
    prellm__llm_provider -->|1| prellm__budget
    prellm__server -->|1| prellm__env_config
    prellm__core -->|1| prellm__pipeline
    prellm__cli -->|1| prellm__models
    prellm__cli -->|1| prellm__logging_setup
    prellm__cli -->|1| prellm__core
    prellm__chains -->|1| prellm__core
